---
deployment:
  tasks:
    - /bin/cp .cpanel.yml /home3/sevenpoi/nodeapps/staging_myconsultation/proof.txt
    - /bin/cp -a . /home3/sevenpoi/nodeapps/staging_myconsultation/
    - /bin/npm install --prefix /home3/sevenpoi/nodeapps/staging_myconsultation/node
