---
deployment:
  tasks:
    - /usr/bin/git clean -fdx
    - export DEPLOYPATH=/home3/sevenpoi/nodeapps/staging_myconsultation
    - /bin/cp -a . $DEPLOYPATH
    - /bin/npm install --prefix $DEPLOYPATH/node
