---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/sevenpoi/nodeapps/staging_myconsultation/
    - /bin/rsync -av --exclude='.git' ./ "${DEPLOYPATH}"
    - /bin/npm install --prefix /home3/sevenpoi/nodeapps/staging_myconsultation/node
