---
deployment:
  tasks:
    - /usr/bin/git clean -fdx
    - /bin/cp -R . /home3/sevenpoi/nodeapps/staging_myconsultation/
    - /bin/npm install --prefix /home3/sevenpoi/nodeapps/staging_myconsultation/node
